version: "0.0.2"
duel:
  length: 120
arena:
  radius: 20.0
challenge:
  cooldown: 30
  hold-shift-required: true
  duel-materials:
  - DIAMOND_SWORD
  - DIAMOND_AXE
  - GOLD_SWORD
  - GOLD_AXE
  - IRON_SWORD
  - IRON_AXE
  - STONE_SWORD
  - STONE_AXE
  - WOOD_SWORD
  - WOOD_AXE