version: "0.0.1"
arena:
  radius: 20.0
challenge:
  hold-shift-required: true
  duel-materials:
  - DIAMOND_SWORD
  - DIAMOND_AXE
  - GOLD_SWORD
  - GOLD_AXE
  - IRON_SWORD
  - IRON_AXE
  - STONE_SWORD
  - STONE_AXE
  - WOOD_SWORD
  - WOOD_AXE